micronaut:
  application:
    name: pixKeyManagerRest
  server:
      port: 8081
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    key-manager-grpc:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10

